groupName: ''

nameOverride: ''

webhook:
  image:
    repository: ghcr.io/sofiaurora270/cert-manager-lego-webhook
    tag: ''
  imagePullPolicy: IfNotPresent
  replicas: 1
  affinity: [ ]
  resources: { }
  envs:
    LEGO_DISABLE_CNAME_SUPPORT: 'true'
  nodeSelector: { }
  extraArgs: [ ]

certManager:
  namespace: ''
  serviceAccountName: cert-manager